//! Cargo (Rust) 依存関係パーサー

use super::{Dependency, ScanDependencies, ScanError};
use std::fs;
use std::path::Path;

/// Cargo.lock をパース
pub fn parse_cargo_lock(path: &Path) -> Result<ScanDependencies, ScanError> {
    let content = fs::read_to_string(path)?;
    let mut dependencies = Vec::new();

    // Cargo.lock is TOML format
    // We'll parse it manually to avoid adding toml crate dependency
    // Format:
    // [[package]]
    // name = "package-name"
    // version = "1.0.0"
    // source = "registry+https://github.com/rust-lang/crates.io-index"

    let mut current_name: Option<String> = None;
    let mut current_version: Option<String> = None;
    let mut in_package_section = false;

    for line in content.lines() {
        let trimmed = line.trim();

        // Start of package section
        if trimmed == "[[package]]" {
            // Save previous package if exists
            if let (Some(name), Some(version)) = (current_name.take(), current_version.take()) {
                dependencies.push(Dependency {
                    name,
                    version,
                    ecosystem: "crates.io".to_string(),
                });
            }
            in_package_section = true;
            continue;
        }

        // Empty line or new section ends current package
        if trimmed.is_empty() || (trimmed.starts_with('[') && trimmed != "[[package]]") {
            if let (Some(name), Some(version)) = (current_name.take(), current_version.take()) {
                dependencies.push(Dependency {
                    name,
                    version,
                    ecosystem: "crates.io".to_string(),
                });
            }
            in_package_section = trimmed == "[[package]]";
            continue;
        }

        if in_package_section {
            // Parse name = "value"
            if let Some(name) = parse_toml_string_value(trimmed, "name") {
                current_name = Some(name);
            } else if let Some(version) = parse_toml_string_value(trimmed, "version") {
                current_version = Some(version);
            }
        }
    }

    // Don't forget the last package
    if let (Some(name), Some(version)) = (current_name, current_version) {
        dependencies.push(Dependency {
            name,
            version,
            ecosystem: "crates.io".to_string(),
        });
    }

    Ok(ScanDependencies {
        ecosystem: "crates.io".to_string(),
        source_file: path.to_string_lossy().to_string(),
        dependencies,
    })
}

/// TOML の string 値をパース
/// 'key = "value"' -> Some("value")
fn parse_toml_string_value(line: &str, key: &str) -> Option<String> {
    let pattern = format!("{} = ", key);
    if line.starts_with(&pattern) {
        let value_part = &line[pattern.len()..];
        // Remove quotes
        let value = value_part
            .trim()
            .trim_start_matches('"')
            .trim_end_matches('"');
        return Some(value.to_string());
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_parse_cargo_lock() {
        let content = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "25dd9975e68d0cb5aa1120c288333fc98731bd1dd12f561e468ea4728c042b89"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "pin-project-lite",
]
"#;

        let mut file = NamedTempFile::new().unwrap();
        file.write_all(content.as_bytes()).unwrap();

        let result = parse_cargo_lock(file.path()).unwrap();
        assert_eq!(result.ecosystem, "crates.io");
        assert_eq!(result.dependencies.len(), 2);
        assert_eq!(result.dependencies[0].name, "serde");
        assert_eq!(result.dependencies[0].version, "1.0.193");
        assert_eq!(result.dependencies[1].name, "tokio");
        assert_eq!(result.dependencies[1].version, "1.35.0");
    }

    #[test]
    fn test_parse_toml_string_value() {
        assert_eq!(
            parse_toml_string_value(r#"name = "serde""#, "name"),
            Some("serde".to_string())
        );
        assert_eq!(
            parse_toml_string_value(r#"version = "1.0.0""#, "version"),
            Some("1.0.0".to_string())
        );
        assert_eq!(parse_toml_string_value(r#"name = "serde""#, "version"), None);
    }
}
