//! Pub (Dart/Flutter) 依存関係パーサー

use super::{Dependency, ScanDependencies, ScanError};
use std::fs;
use std::path::Path;

/// pubspec.lock をパース (YAML形式)
pub fn parse_pubspec_lock(path: &Path) -> Result<ScanDependencies, ScanError> {
    let content = fs::read_to_string(path)?;
    let mut dependencies = Vec::new();

    let mut in_packages_section = false;
    let mut current_package: Option<String> = None;
    let mut current_version: Option<String> = None;

    for line in content.lines() {
        // Detect packages section
        if line == "packages:" {
            in_packages_section = true;
            continue;
        }

        // New top-level section (no indentation)
        if !line.starts_with(' ') && !line.is_empty() && line != "packages:" {
            in_packages_section = false;
            continue;
        }

        if in_packages_section {
            // Package name (2 spaces indentation)
            // "  flutter:"
            if line.starts_with("  ") && !line.starts_with("    ") {
                // Save previous package
                if let (Some(name), Some(version)) = (current_package.take(), current_version.take()) {
                    dependencies.push(Dependency {
                        name,
                        version,
                        ecosystem: "Pub".to_string(),
                    });
                }

                // Parse new package name
                let trimmed = line.trim();
                if let Some(name) = trimmed.strip_suffix(':') {
                    current_package = Some(name.to_string());
                    current_version = None;
                }
            }

            // Version field (4 spaces indentation)
            // "    version: \"1.0.0\""
            if line.starts_with("    version:") {
                let version_part = line.trim().strip_prefix("version:").unwrap_or("").trim();
                // Remove quotes if present
                let version = version_part.trim_matches('"').trim_matches('\'');
                if !version.is_empty() {
                    current_version = Some(version.to_string());
                }
            }
        }
    }

    // Don't forget the last package
    if let (Some(name), Some(version)) = (current_package, current_version) {
        dependencies.push(Dependency {
            name,
            version,
            ecosystem: "Pub".to_string(),
        });
    }

    Ok(ScanDependencies {
        ecosystem: "Pub".to_string(),
        source_file: path.to_string_lossy().to_string(),
        dependencies,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_parse_pubspec_lock() {
        let content = r#"# Generated by pub
packages:
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"
"#;

        let mut file = NamedTempFile::new().unwrap();
        file.write_all(content.as_bytes()).unwrap();

        let result = parse_pubspec_lock(file.path()).unwrap();
        assert_eq!(result.ecosystem, "Pub");
        assert_eq!(result.dependencies.len(), 3);

        let args = result.dependencies.iter().find(|d| d.name == "args").unwrap();
        assert_eq!(args.version, "2.3.1");
    }
}
